# Generated by Django 2.0.4 on 2018-09-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180901_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_by',
        ),
    ]
