# Generated by Django 2.0.4 on 2018-08-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='language',
        ),
    ]
