# Generated by Django 2.0.4 on 2018-09-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0009_auto_20180907_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktransactionmodel',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booklist.Book'),
            preserve_default=False,
        ),
    ]
