# Generated by Django 2.0.4 on 2018-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0010_booktransactionmodel_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktransactionmodel',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
